services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: jarvis-database
      POSTGRES_USER: jarvis-database-user
      POSTGRES_PASSWORD: jarvis-database-password
    ports:
      - '5432:5432'
    networks:
      - jarvis-network

  mailpit:
    image: axllent/mailpit
    container_name: jarvis-mailpit
    restart: unless-stopped
    ports:
      - '8025:8025'
      - '1025:1025'
    volumes:
      - mailpit-data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - jarvis-network

networks:
  jarvis-network:
    driver: bridge

volumes:
  mailpit-data:
    driver: local
