export enum ErrorCodes {
  UNKNOWN_ERROR = 'S001',
  VALIDATION_ERROR = 'S002',
  TRUCK_NOT_FOUND = 'T001',
  TRUCK_ALREADY_EXISTS = 'T002',
  TRUCK_RETRIEVAL_FAILED = 'T003',
  TRUCK_LISTING_FAILED = 'T004',
  TRUCK_CREATION_FAILED = 'T005',
  TRUCK_UPDATE_FAILED = 'T006',
  TRUCK_DELETION_FAILED = 'T007',
  TRUCK_PERSISTENCE_ERROR = 'T008',
  USER_NOT_FOUND = 'U001',
  USER_ALREADY_EXISTS = 'U002',
  INVALID_CREDENTIALS = 'U003',
  USER_CREATION_FAILED = 'U004',
  USER_AUTH_FAILED = 'U005',
  USER_PERSISTENCE_ERROR = 'U006',
  WORKSPACE_NOT_FOUND = 'W001',
  WORKSPACE_ALREADY_EXISTS = 'W002',
  WORKSPACE_SLUG_ALREADY_EXISTS = 'W003',
  WORKSPACE_CREATION_FAILED = 'W004',
  WORKSPACE_UPDATE_FAILED = 'W005',
  WORKSPACE_DELETION_FAILED = 'W006',
  WORKSPACE_RETRIEVAL_FAILED = 'W007',
  WORKSPACE_LISTING_FAILED = 'W008',
  WORKSPACE_PERSISTENCE_ERROR = 'W009',
}

export enum ErrorTitles {
  UNKNOWN_ERROR = 'Unknown error',
  VALIDATION_ERROR = 'Validation error',
  TRUCK_NOT_FOUND = 'Truck not found',
  TRUCK_ALREADY_EXISTS = 'Truck already exists',
  TRUCK_RETRIEVAL_FAILED = 'Truck retrieval failed',
  TRUCK_LISTING_FAILED = 'Truck listing failed',
  TRUCK_CREATION_FAILED = 'Truck creation failed',
  TRUCK_UPDATE_FAILED = 'Truck update failed',
  TRUCK_DELETION_FAILED = 'Truck deletion failed',
  TRUCK_PERSISTENCE_ERROR = 'Truck persistence error',
  USER_NOT_FOUND = 'User not found',
  USER_ALREADY_EXISTS = 'User already exists',
  INVALID_CREDENTIALS = 'Invalid credentials',
  USER_CREATION_FAILED = 'User creation failed',
  USER_AUTH_FAILED = 'User authentication failed',
  USER_PERSISTENCE_ERROR = 'User persistence error',
  WORKSPACE_NOT_FOUND = 'Workspace not found',
  WORKSPACE_ALREADY_EXISTS = 'Workspace already exists',
  WORKSPACE_SLUG_ALREADY_EXISTS = 'Workspace slug already exists',
  WORKSPACE_CREATION_FAILED = 'Workspace creation failed',
  WORKSPACE_UPDATE_FAILED = 'Workspace update failed',
  WORKSPACE_DELETION_FAILED = 'Workspace deletion failed',
  WORKSPACE_RETRIEVAL_FAILED = 'Workspace retrieval failed',
  WORKSPACE_LISTING_FAILED = 'Workspace listing failed',
  WORKSPACE_PERSISTENCE_ERROR = 'Workspace persistence error',
}

export enum ErrorMessages {
  UNKNOWN_ERROR = 'An unknown error occurred.',
  VALIDATION_ERROR = 'Validation failed.',
  TRUCK_NOT_FOUND = 'The truck with the given ID was not found.',
  TRUCK_ALREADY_EXISTS = 'The truck with the given license plate already exists.',
  TRUCK_RETRIEVAL_FAILED = 'Failed to retrieve the truck.',
  TRUCK_LISTING_FAILED = 'Failed to list trucks.',
  TRUCK_CREATION_FAILED = 'Failed to create the truck.',
  TRUCK_UPDATE_FAILED = 'Failed to update the truck.',
  TRUCK_DELETION_FAILED = 'Failed to delete the truck.',
  TRUCK_PERSISTENCE_ERROR = 'A database error occurred while persisting truck data.',
  USER_NOT_FOUND = 'The user with the given ID was not found.',
  USER_ALREADY_EXISTS = 'A user with the given email or phone already exists.',
  INVALID_CREDENTIALS = 'Invalid email or password.',
  USER_CREATION_FAILED = 'Failed to create the user.',
  USER_AUTH_FAILED = 'Failed to authenticate the user.',
  USER_PERSISTENCE_ERROR = 'A database error occurred while persisting user data.',
  WORKSPACE_NOT_FOUND = 'The workspace with the given ID was not found.',
  WORKSPACE_ALREADY_EXISTS = 'A workspace with the given name already exists.',
  WORKSPACE_SLUG_ALREADY_EXISTS = 'A workspace with the given slug already exists.',
  WORKSPACE_CREATION_FAILED = 'Failed to create the workspace.',
  WORKSPACE_UPDATE_FAILED = 'Failed to update the workspace.',
  WORKSPACE_DELETION_FAILED = 'Failed to delete the workspace.',
  WORKSPACE_RETRIEVAL_FAILED = 'Failed to retrieve the workspace.',
  WORKSPACE_LISTING_FAILED = 'Failed to list workspaces.',
  WORKSPACE_PERSISTENCE_ERROR = 'A database error occurred while persisting workspace data.',
}
